languageCode = "en-us"
title = "Facted"
theme = "dimension"
canonifyURLs = true
baseURL = /

[params]
  title = "Facted"
  description = "Take pictures that are independently verifiable proven facts"
  logo = "fa-diamond"
  copyright = "1AmOXsGnfXdbNg3RMTyPCHkn2aT"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/facted_net"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/pg/Facted-372487459798987"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/facted_net"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/facted-net"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://medium.com/facted"
